### ISSUE TITLE
See previous chat histories

### ISSUE THREAD

**Issue by lourenci** [alfredapp/openai-workflow#10]
### Feature details

We'd like to navigate between all the new conversations we had with ChatGPT and be able to view/continue that conversation. Is that on the roadmap, by any chance?

**Comment by vitorgalvao** [comment]
It is something I have considered and thought about, but it has considerations interface-wise and it’s not as popular of a request as you might think (I’m not sure who you mean by “we”, as you’re the first person to ask for it). It may come in the future but no promises as it’s not the focus right now. It may even exist in a different form.

**Comment by vitorgalvao** [comment]
@lourenci Just to let you know this is now available.
