### ISSUE TITLE
Error when using cf-openai-azure-proxy

### ISSUE THREAD

**Issue by HuaDeity** [alfredapp/openai-workflow#11]
### Workflow version

2024.5

### Alfred version

5.5 [2257]

### macOS version

Sonoma 14.4

### Debugger output

```alfred_debugger
[11:27:09.690] ERROR: ChatGPT / DALL-E[Text View] Code 1: /Users/huadeity/Library/CloudStorage/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.3EFAE712-0A37-4377-8DC8-A487A6F6658C/chatgpt: execution error: Error: TypeError: undefined is not an object (evaluating 'item["choices"][0]["delta"]') (-2700)
```

### More details

I used [cf-openai-azure-proxy](https://github.com/haibbo/cf-openai-azure-proxy) to proxy Azure OpenAI for using Workflow.

The top three data in stream.txt is:
```
data: {"id":"","object":"","created":0,"model":"","prompt_filter_results":[{"prompt_index":0,"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}}}],"choices":[]}

data: {"id":"chatcmpl-94KQ1fkLhyMRL11BnpYZrD0mc64Lm","object":"chat.completion.chunk","created":1710818829,"model":"gpt-35-turbo","choices":[{"finish_reason":null,"index":0,"delta":{"role":"assistant","content":""},"content_filter_results":{}}]}

data: {"id":"chatcmpl-94KQ1fkLhyMRL11BnpYZrD0mc64Lm","object":"chat.completion.chunk","created":1710818829,"model":"gpt-35-turbo","choices":[{"finish_reason":null,"index":0,"delta":{"content":"Hello"},"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}}}]}
```

I believe the error may be related to the first response not having the "delta" value under item["choices"][0], as indicated by the ERROR message. Additionally, it appears that this response is missing other necessary keys such as "id" and "object". To resolve this issue, we could consider checking for the presence of an "id" key in order to skip over the first response.

**Comment by vitorgalvao** [comment]
https://www.alfredforum.com/topic/21483-chatgpt-dall-e-openai-integrations/

> This workflow also offers the ability to change the API end point in the [Workflow Environment Variables](https://www.alfredapp.com/help/workflows/advanced/variables/#environment), enabling the possibility of using local models. This is complex and requires advanced configuration, not something we can provide support for. Having said that, our community are already doing this and can help you on a different thread:
> 
> https://www.alfredforum.com/topic/21544-using-local-models-with-chatgpt-dall-e-workflow/

**Comment by HuaDeity** [comment]
@vitorgalvao 

Using #12 can resolve this issue. Just ensure to check if `item["choices"][0]["delta"]["content"]` exists before accessing it. This will not affect any other use case.

**Comment by vitorgalvao** [comment]
Closing in favour of the conversation in #12.
