### ISSUE TITLE
Can I use a custom host？

### ISSUE THREAD

**Issue by est7** [alfredapp/openai-workflow#14]
### Feature details

My api key is Azure, can I set a custom host? Thanks

**Comment by vitorgalvao** [comment]
[Explained in the forum](https://www.alfredforum.com/topic/21483-chatgpt-dall-e-openai-integrations/?do=findComment&comment=111557). Use the Workflow Environment Variables.

**Comment by HuaDeity** [comment]
@est7 

you need to use proxy to transform openai api request to azure openai api request.
