### ISSUE TITLE
Support custom OpenAI API base URL

### ISSUE THREAD

**Issue by tddschn** [alfredapp/openai-workflow#18]
### Feature details

I'm using OpenAI with a non-default base URL, not `openai.com/api/v1`. Could you please support using non-default API base as an option in the workflow? Thanks!

**Comment by vitorgalvao** [comment]
See https://github.com/alfredapp/openai-workflow/issues/14.

If that’s not what you’re looking for, please explain your issue in more detail, including adding the URL you’re using and why it’s different.

**Comment by tddschn** [comment]
Thank you, I didn't check the env var section of the workflow. Setting the env var worked for me!
