### ISSUE TITLE
Universal Action: Start a New Chat

### ISSUE THREAD

**Issue by Ga68** [alfredapp/openai-workflow#20]
### Feature details

**Request**: I'd love a second universal action that allows me to send in text and start straight from a new, clean chat with GPT. Right now the universal action appends to the prior.

I tried to do this myself, but I'm getting a behavior I can't sort out. It works, but the text area doesn't pop up until the full answer has been streamed. So unlike for the existing universal action, and unlike for when you do it "in workflow", it sits "silently" (appearing if nothing is going on) and then the text area pops open with the question and answer fully populated.

My attempt was to add a universal action node (New Question for GPT) that connected to a variable set to put the query into the same variable as the normal flow (init_question), and then connected into the chat.json node where the contents are reset.

Love this workflow. Thanks so much for making it.

**Comment by vitorgalvao** [comment]
There’s no need for a second Universal Action, only adding a second connection to the one already there. Will be in the next version.

**Comment by Ga68** [comment]
Thanks so much for getting this in! I see it in 2024.6
