### ISSUE TITLE
connectionless

### ISSUE THREAD

**Issue by wxywizard** [alfredapp/openai-workflow#22]
### Workflow version

Version 2024.5

### Alfred version

Alfred 5.5

### macOS version

14.4.1 (23E224)

### Debugger output

```alfred_debugger
When I use the current workflows the link fails to report an error, probably because of the proxy problem, but I have a local proxy for the openai related domain, what address should I add a proxy for when I use it in alfred?
```

### More details

![CleanShot 2024-04-02 at 13 56 02@2x](https://github.com/alfredapp/openai-workflow/assets/28422371/2ef8b870-165d-4b32-a134-ac156fb97087)

**Comment by vitorgalvao** [comment]
That is not the [debugger](https://www.alfredapp.com/help/workflows/advanced/debugger/) output.

> what address should I add a proxy for when I use it in alfred?

The proxy address is something you’ll have yourself. That is something local to your machine that I’m unable to help debug.

The [second post in the forum](https://www.alfredforum.com/topic/21483-chatgpt-dall-e-openai-integrations/?do=findComment&comment=111557) explains how to set it up.

Also, [try the latest preview release](https://www.alfredforum.com/topic/21483-chatgpt-dall-e-openai-integrations/?do=findComment&comment=112621).
