### ISSUE TITLE
Locally hosted AI

### ISSUE THREAD

**Issue by terencehorsman** [alfredapp/openai-workflow#23]
### Feature details

Love this new Alfred workflow, well done on the implementation. 

It got me thinking: OpenAI API tokens always come at a cost. Furthermore, you have to be connected to the web. What if we could swap API calls to OpenAI to talk to a locally running AI service instead? Thinking we could use Ollama for this, make native API calls and listen to the input stream: https://github.com/ollama/ollama

Once Ollama is running, which we could start with bash, we can make API calls such as 

POST http://127.0.0.1:11434/api/chat
{
  "model": "llama2",
  "messages": [
    { "role": "user", "content": "what is the difference between chatGPT and llama?" }
  ],
  "stream": true
}

We can most likely re-use a lot of the GPT listen and display code? 

Happy to help with the implementation.
Terence

**Comment by vitorgalvao** [comment]
This has been available for a while, [details are in the forum](https://www.alfredforum.com/topic/21483-chatgpt-dall-e-openai-integrations/#comment-111557).

Use [the latest preview](https://www.alfredforum.com/topic/21483-chatgpt-dall-e-openai-integrations/page/3/#comment-112621) to also have a way to override the model.
