### ISSUE TITLE
Update to v2024.6 doesn't seem to work

### ISSUE THREAD

**Issue by maxim** [alfredapp/openai-workflow#24]
### Frequently Asked Questions

- [X] I have [read the FAQ](https://www.alfredforum.com/topic/21483-chatgpt-dall-e-openai-integrations/#comment-111557) before opening the issue.

### Workflow version

v2024.5

### Alfred version

5.5 [2257]

### macOS version

Sonoma 14.4.1

### Debugger output

```alfred_debugger
[16:28:20.511] Logging Started...
```

(nothing else shows up)

### More details

When I go to Settings -> Workflows, right click on ChatGPT / DALL-E, and click "Update from Alfred Gallery", I see the dialog showing up showing the settings for adjusting. However, when I press Update on this dialog, it goes away, but the workflow stays not-updated (same version).

Also interesting: right clicking on that workflow in Alfred to show the menu no longer works (menu doesn't appear). I have to close and reopen settings to be able to right click a workflow.

**Comment by vitorgalvao** [comment]
That’s not related to the Workflow, as the update is done via Alfred. Are you syncing your settings? [Make sure the Alfred Preferences are available offline](https://www.alfredapp.com/help/advanced/sync/#always-offline).

Delete the workflow and [install it again](https://alfred.app/workflows/alfredapp/openai/).
