### ISSUE TITLE
Do not auto send the prompt in the new chat, just populate the input field

### ISSUE THREAD

**Issue by pravdomil** [alfredapp/openai-workflow#29]
### Frequently Asked Questions

- [X] I have [read the FAQ](https://www.alfredforum.com/topic/21483-chatgpt-dall-e-openai-integrations/#comment-111557) before opening the issue.

### Feature details

when pressing Cmd + Enter in chat view

**Comment by vitorgalvao** [comment]
This is not possible with the current functionality. Again, I ask that you read up on [how the Text View works](https://www.alfredapp.com/help/workflows/user-interface/text/).

In addition, starting a new chat is by design, that was a request feature. That’s what works best for most users.
