### ISSUE TITLE
Use ⌥↩ for new line and Shift↩ for copy last

### ISSUE THREAD

**Issue by pravdomil** [alfredapp/openai-workflow#30]
### Frequently Asked Questions

- [X] I have [read the FAQ](https://www.alfredforum.com/topic/21483-chatgpt-dall-e-openai-integrations/#comment-111557) before opening the issue.

### Feature details

there is no way how to make new line

**Comment by vitorgalvao** [comment]
As per the other issue, there are currently no plans to change the default shortcuts. But you can use <kbd>⇧</kbd><kbd>⌥</kbd><kbd>↩</kbd> to add a new line. Please consider that there are a lot of users of this workflow, and simple shortcuts for the most common tasks are important.

**Comment by pravdomil** [comment]
Please consider that there are a lot of users of this workflow, and shortcuts consistency across macOS applications for the most common tasks are important.

**Comment by pravdomil** [comment]
it is confusing by design and we have no intent to make better
