### ISSUE TITLE
Render latex math outputted by ChatGPT as math

### ISSUE THREAD

**Issue by dblarons** [alfredapp/openai-workflow#39]
### Frequently Asked Questions

- [X] I have [read the FAQ](https://www.alfredforum.com/topic/21483-chatgpt-dall-e-openai-integrations/#comment-111557) before opening the issue.

### Feature details

Most of my ChatGPT searches include math formulas, either inline or on their own line.

The workflow plugin doesn't render the math formulas provided by ChatGPT as math formulas regardless of whether they are inline or on their own line.

Here is an example of an inline formula displayed in Alfred:
<img width="497" alt="image" src="https://github.com/alfredapp/openai-workflow/assets/1482167/cbe2f40f-c098-4728-83e9-fe4f3bb38951">

and the raw markdown code:
```
1. **Compute the Update Gate \( zᵗ \)**:
\[ zᵗ = σ(Wᶻ \cdot [h^{t-1}, xᵗ]) \]
Here, \( σ \) is the sigmoid activation function, \( xᵗ \) is the input at time step \( t \), \( h^{t-1} \) is the hidden state from the previous time step, and \( Wᶻ \) is the weight matrix for the update gate.
```

Here is an example of a formula on it's own line in Alfred:
<img width="494" alt="image" src="https://github.com/alfredapp/openai-workflow/assets/1482167/7edfa733-cae8-4145-958c-46d4c1d062df">

In Github Markdown, you are able to render latex math by wrapping your text with `$` for an inline equation or `$$` for a block:

> 1. **Compute the Update Gate $zᵗ$:** 
> $zᵗ = σ(Wᶻ \cdot [h^{t-1}, xᵗ])$ 
> Here, $σ$ is the sigmoid activation function, $xᵗ$ is the input at time step $t$, $h^{t-1}$ is the hidden state from the previous time step, and $Wᶻ$ is the weight matrix for the update gate.

> $$\frac{d^2y}{dt^2} + \omega^2 y = 0$$

Converting this required replacing the instances of `\(`, `\)`, `\[`, and `\]` with either `$` or `$$`. 

I tested using the `$` syntax in the Alfred notes workflow plugin, and it didn't appear to work:
<img width="263" alt="image" src="https://github.com/alfredapp/openai-workflow/assets/1482167/617dfb06-0a6c-4a77-b827-a43d63cec5ef">

In any event, it looks like the ChatGPT plugin may need to be updated to support substituting the latex symbols for markdown symbols, and whatever text field and markdown code within Alfred itself may need to be updated to support the `$` symbol like Github markdown does.

I am aware that you can ask ChatGPT to return the math in a different format, but I have found that to be hit or (mostly) miss. I hope you can consider supporting this because in this is my number one use case and I've had to switch back to the ChatGPT website.

MacOS Ventura 13.6.7
Alfred 5.5
OpenAI Workflow v2024.11

**Comment by vitorgalvao** [comment]
This is not something which can be supported in the workflow itself. [The rendering is done by Alfred.](https://www.alfredapp.com/help/kb/markdown-syntax/)
