### ISSUE TITLE
Add  functionality to export answer(s) to clipboard as markdown

### ISSUE THREAD

**Issue by dgdosen** [alfredapp/openai-workflow#4]
### Feature details

I've never built an Alfred Workflow, but I'd like to take the content of an answer and copy into markdown... Is this idea a logical idea for Alfred?

Is this something one could develop as an extension to your workflow?

**Comment by vitorgalvao** [comment]
You can already copy the workflow’s answers as Markdown. Shortcuts are in the documentation and at the bottom of the window.

**Comment by dgdosen** [comment]
apologies... I didn't even try it and I assumed it wasn't markdown.
