### ISSUE TITLE
Reuse pre-made prompts

### ISSUE THREAD

**Issue by notDavid** [alfredapp/openai-workflow#40]
Hi there,

i've read [reuse pre-made prompts](https://www.alfredforum.com/topic/21483-chatgpt-dall-e-openai-integrations/#comment-111557) and i'm curious whether it's on the roadmap to include custom prompts in this Workflow itself? And if so, is there an estimated release date?

Thank you!

**Comment by vitorgalvao** [comment]
Hello,

There is not. The point of that instruction is that anyone can make the custom prompts they want, as many or as few as they want, and make them work however they want.
