### ISSUE TITLE
Support for GPT 4o mini

### ISSUE THREAD

**Issue by clo4** [alfredapp/openai-workflow#41]
### Frequently Asked Questions

- [X] I have [read the FAQ](https://www.alfredforum.com/topic/21483-chatgpt-dall-e-openai-integrations/#comment-111557) before opening the issue.

### Feature details

OpenAI have [announced gpt-4o-mini](https://openai.com/index/gpt-4o-mini-advancing-cost-efficient-intelligence/), a 'smarter' and more cost effective model than gpt-3.5-turbo. The naming they use is `GPT-4o mini` (what's up with companies not capitalising the word 'mini'???), the model string is `gpt-4o-mini`.

OpenAI is replacing 3.5 Turbo with 4o mini in ChatGPT, I think it might also make sense to set this as the default going forward?

**Comment by vitorgalvao** [comment]
Thank you for the heads-up. Replaced in 2024.13, just released.
