### ISSUE TITLE
Request to add API hosting options

### ISSUE THREAD

**Issue by tonychen99** [alfredapp/openai-workflow#45]
### Frequently Asked Questions

- [X] I have [read the FAQ](https://www.alfredforum.com/topic/21483-chatgpt-dall-e-openai-integrations/#comment-111557) before opening the issue.

### Feature details

Since I'm using non-openai api hosts such as deepbricks, I'd like to suggest an option to add an api host to accommodate keys that are not officially acquired by openai but are compatible with the openai api standard, and I'd like to add an option to add an api host to accommodate keys that are not officially acquired by openai but are compatible with the openai api standard.Thank you very much and look forward to seeing that improvement in the future!

**Comment by vitorgalvao** [comment]
Please read the FAQ. All that is and will be supported in that regard, how, and why, is right on the first item.
