### ISSUE TITLE
Cmd Key with Universal Action Doesn't Start New Chat

### ISSUE THREAD

**Issue by egornomic** [alfredapp/openai-workflow#46]
### Frequently Asked Questions

- [X] I have [read the FAQ](https://www.alfredforum.com/topic/21483-chatgpt-dall-e-openai-integrations/#comment-111557) before opening the issue.

### Workflow version

2024.13

### Alfred version

not relevant

### macOS version

not relevant

### Debugger output

```alfred_debugger
not relevant
```

### Issue
- **Description:** Cmd key with universal action fails to initiate a new clear chat.

### Fix
- **Change:** Set `new_chat` to 0 in the bottom branch of the universal action trigger.

**Comment by vitorgalvao** [comment]
What I’m seeing is the opposite: it always starts with a new chat even if <kbd>⌘</kbd> isn’t pressed. Will be fixed in the next release. Thank you.
