### ISSUE TITLE
New o1 models doesn't suppport stream

### ISSUE THREAD

**Issue by mohithg** [alfredapp/openai-workflow#47]
### Frequently Asked Questions

- [X] I have [read the FAQ](https://www.alfredforum.com/topic/21483-chatgpt-dall-e-openai-integrations/#comment-111557) before opening the issue.

### Workflow version

2024.15

### Alfred version

5.5 [2257]

### macOS version

12.7.4

### Debugger output

```alfred_debugger
[Unsupported value: 'stream' does not support true with this model. Only the default (false) value is supported.]
```

**Comment by vitorgalvao** [comment]
Thank you for the report. Looks like this is a specific limitation of the betas and is not the only unavailable feature. Streaming is a core part of how the workflow works and changing it to support non-streaming would require a number of changes. I’m wary of doing that and messing with the stability and usefulness of the workflow (not streaming is already slow as molasses, and the new models even more so) only to support what looks to be a temporary limitation on a beta that a large number of people won’t have access to, so for now I’m removing the models.
