### ISSUE TITLE
Support setting network proxy for this workflow (wokflow level) 

### ISSUE THREAD

**Issue by diligentpig** [alfredapp/openai-workflow#6]
### Feature details

Thanks @vitorgalvao for the great work, this generative AI finally arrives in Alfred!

Since OpenAI is not available in some countries/regions, would it be possible to enhance this workflow to have a dedicated network proxy setting? E.g. https/socks. Although Alfred can utilize the system proxy in macOS, setting a system proxy would affect all other apps.

If possible, the workflow environment variables seem to be a good place for this setting.

**Comment by vitorgalvao** [comment]
Thank you for the feature request. I will consider it depending on overall need but [that is not planned *right now*](https://www.alfredforum.com/topic/21483-chatgpt-dall-e-openai-integrations/#comment-111628) (I did not ignore the request, that answer was meat to cover all).

Though I will ask that you not make the same request repeatedly or ping directly. That inundates my mentions and makes it harder to help anyone.

Thank you.
