### ISSUE TITLE
Support for other models like `gpt-4-turbo-preview`

### ISSUE THREAD

**Issue by joelee** [alfredapp/openai-workflow#7]
### Feature details

Please allow the option to enter free text in the GPT Model settings so that we can use other GPT models.

![image](https://github.com/alfredapp/openai-workflow/assets/217132/d46d958e-891f-4fad-80f0-cd3e17c040e3)

**Comment by vitorgalvao** [comment]
Thank you for the feature request. Something like that may come, but probably not in the form of a free form text box. While you may know exactly which models to insert, most users won’t and that will make configuration hard for them.

There are so many different knobs and dials that an early explicit goal of this workflow remains to avoid configuration fatigue. Right this moment the operative word is *focus* and carefully choosing what makes the biggest impact for the largest number of users.
